<?php

namespace User\UserBundle\Repository;

/**
 * aNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aNewsRepository extends \Doctrine\ORM\EntityRepository
{
}
