admin_pub:
    resource: "@AdminPubBundle/Resources/config/routing.yml"
    prefix:   /adminPub

pub:
    resource: "@PubBundle/Resources/config/routing.yml"
    prefix:   /Pub

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

admin_event:
    resource: "@adminEventBundle/Resources/config/routing.yml"
    prefix:   /adminCart

admin_cart:
    resource: "@AdminCartBundle/Resources/config/routing.yml"
    prefix:   /adminCart

cart:
    resource: "@CartBundle/Resources/config/routing.yml"
    prefix:   /cart

admin_sav:
    resource: "@AdminSAVBundle/Resources/config/routing.yml"
    prefix:   /adminSav

sav:
    resource: "@SAVBundle/Resources/config/routing.yml"
    prefix:   /sav
admin_boutique:
    resource: "@AdminBoutiqueBundle/Resources/config/routing.yml"
    prefix:   /adminBoutique

boutique:
    resource: "@BoutiqueBundle/Resources/config/routing.yml"
    prefix:   /boutique

admin_emergency:
    resource: "@AdminEmergencyBundle/Resources/config/routing.yml"
    prefix:   /adminEmergency

emergency:
    resource: "@EmergencyBundle/Resources/config/routing.yml"
    prefix:   /emergency

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
