admin_emergency_homepage:
    path:     /
    defaults: { _controller: AdminEmergencyBundle:Default:index }
admin_emergency_prevention:
    path:     /prevention
    defaults: { _controller: AdminEmergencyBundle:Default:prevention }
admin_emergency_prevention_detailExp:
    path:     /prevention_detailExp/{id}
    defaults: { _controller: AdminEmergencyBundle:Default:prevention_detailExp }
admin_emergency_prevention_archExp:
    path:     /prevention_delExp/{id}
    defaults: { _controller: AdminEmergencyBundle:Default:prevention_archExp }
admin_emergency_traiter:
    path:     /emergency_traiter/{id}
    defaults: { _controller: AdminEmergencyBundle:Default:emergency_traiter }