<?php

namespace Pub\PubBundle\Repository;

/**
 * pubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pubRepository extends \Doctrine\ORM\EntityRepository
{
}
