<?php

namespace SAV\SAVBundle\Repository;

/**
 * NotificationssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationssRepository extends \Doctrine\ORM\EntityRepository
{
}
