<?php

namespace Emergency\AdminEmergencyBundle\Repository;

/**
 * ExpeditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpeditionRepository extends \Doctrine\ORM\EntityRepository
{
}
